name: "build_deploy_app"

on:
    push:
        branches:
            - master

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            - name: "Build:checkout"
              uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - name: "Build:download"
              run: yarn
            - name: "Build:dockerimage"
              uses: docker/build-push-action@v1
              with:
                  registry: ghcr.io
                  username: "DavidIlie"
                  password: ${{ secrets.GHCR_PASSWORD }}
                  repository: davidilie/octoprint-camera-ui
                  tags: latest
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Kubernetes
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout restart deploy octoprint-camera-ui -n internal
